# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Cypress Tests Local - Results XRAY

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      DEVICE:
        description: 'Device the tests shall run on'
        required: true
        default: DESKTOP
        type: choice
        options:
          - DESKTOP
          - IPHONE_12_PRO
          - S20_ULTRA
          - IPAD_AIR

      RUN_NAME:
        description: 'The name of the run'
        required: true
        default: 'Regression'

      TAGS:
        description: 'Execute tests with specified tag/s'
        required: true
        default: 'Regression'

      XRAY_RUN:
        description: 'Push run results to XRAY'
        required: true
        default: true
        type: boolean

      BROWSER:
        description: 'Browser that tests will run on'
        required: true
        default: chrome
        type: choice
        options:
            - chrome
            - electron
            - firefox

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      # Run Cypress tests
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install modules
        run: npm install

      - name: Copy variables to global env
        run: |
          echo "RUN_NAME=${{ inputs.RUN_NAME}}" >> $GITHUB_ENV
          echo "DEVICE=${{ inputs.DEVICE}}" >> $GITHUB_ENV
          echo "XRAY_CLIENT_ID=${{ secrets.XRAY_CLIENT_ID }}" >> $GITHUB_ENV
          echo "XRAY_CLIENT_SECRET=${{ secrets.XRAY_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "JIRA_API_TOKEN=${{ secrets.JIRA_API_TOKEN }}" >> $GITHUB_ENV
          echo "BROWSER=${{ inputs.BROWSER }}" >> $GITHUB_ENV
          echo "TAGS=${{ inputs.TAGS }}" >> $GITHUB_ENV
          echo "XRAY_RUN=${{ inputs.XRAY_RUN }}" >> $GITHUB_ENV
          echo "JIRA_USERNAME=${{ vars.JIRA_USERNAME }}" >> $GITHUB_ENV

      - name: Print env
        run: env

      - name: Cypress run
        run:  DEVICE=$DEVICE CYPRESS_INCLUDE_TAGS=$TAGS npx cypress run --browser $BROWSER
